// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"finhub-go/internal/ent/paymentstatus"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PaymentStatusCreate is the builder for creating a PaymentStatus entity.
type PaymentStatusCreate struct {
	config
	mutation *PaymentStatusMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (psc *PaymentStatusCreate) SetCreatedAt(t time.Time) *PaymentStatusCreate {
	psc.mutation.SetCreatedAt(t)
	return psc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (psc *PaymentStatusCreate) SetNillableCreatedAt(t *time.Time) *PaymentStatusCreate {
	if t != nil {
		psc.SetCreatedAt(*t)
	}
	return psc
}

// SetUpdatedAt sets the "updated_at" field.
func (psc *PaymentStatusCreate) SetUpdatedAt(t time.Time) *PaymentStatusCreate {
	psc.mutation.SetUpdatedAt(t)
	return psc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (psc *PaymentStatusCreate) SetNillableUpdatedAt(t *time.Time) *PaymentStatusCreate {
	if t != nil {
		psc.SetUpdatedAt(*t)
	}
	return psc
}

// SetName sets the "name" field.
func (psc *PaymentStatusCreate) SetName(s string) *PaymentStatusCreate {
	psc.mutation.SetName(s)
	return psc
}

// SetDescription sets the "description" field.
func (psc *PaymentStatusCreate) SetDescription(s string) *PaymentStatusCreate {
	psc.mutation.SetDescription(s)
	return psc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (psc *PaymentStatusCreate) SetNillableDescription(s *string) *PaymentStatusCreate {
	if s != nil {
		psc.SetDescription(*s)
	}
	return psc
}

// SetID sets the "id" field.
func (psc *PaymentStatusCreate) SetID(u uuid.UUID) *PaymentStatusCreate {
	psc.mutation.SetID(u)
	return psc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (psc *PaymentStatusCreate) SetNillableID(u *uuid.UUID) *PaymentStatusCreate {
	if u != nil {
		psc.SetID(*u)
	}
	return psc
}

// Mutation returns the PaymentStatusMutation object of the builder.
func (psc *PaymentStatusCreate) Mutation() *PaymentStatusMutation {
	return psc.mutation
}

// Save creates the PaymentStatus in the database.
func (psc *PaymentStatusCreate) Save(ctx context.Context) (*PaymentStatus, error) {
	psc.defaults()
	return withHooks(ctx, psc.sqlSave, psc.mutation, psc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (psc *PaymentStatusCreate) SaveX(ctx context.Context) *PaymentStatus {
	v, err := psc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (psc *PaymentStatusCreate) Exec(ctx context.Context) error {
	_, err := psc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (psc *PaymentStatusCreate) ExecX(ctx context.Context) {
	if err := psc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (psc *PaymentStatusCreate) defaults() {
	if _, ok := psc.mutation.CreatedAt(); !ok {
		v := paymentstatus.DefaultCreatedAt()
		psc.mutation.SetCreatedAt(v)
	}
	if _, ok := psc.mutation.UpdatedAt(); !ok {
		v := paymentstatus.DefaultUpdatedAt()
		psc.mutation.SetUpdatedAt(v)
	}
	if _, ok := psc.mutation.ID(); !ok {
		v := paymentstatus.DefaultID()
		psc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (psc *PaymentStatusCreate) check() error {
	if _, ok := psc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentStatus.created_at"`)}
	}
	if _, ok := psc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentStatus.updated_at"`)}
	}
	if _, ok := psc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PaymentStatus.name"`)}
	}
	if v, ok := psc.mutation.Name(); ok {
		if err := paymentstatus.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PaymentStatus.name": %w`, err)}
		}
	}
	return nil
}

func (psc *PaymentStatusCreate) sqlSave(ctx context.Context) (*PaymentStatus, error) {
	if err := psc.check(); err != nil {
		return nil, err
	}
	_node, _spec := psc.createSpec()
	if err := sqlgraph.CreateNode(ctx, psc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	psc.mutation.id = &_node.ID
	psc.mutation.done = true
	return _node, nil
}

func (psc *PaymentStatusCreate) createSpec() (*PaymentStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentStatus{config: psc.config}
		_spec = sqlgraph.NewCreateSpec(paymentstatus.Table, sqlgraph.NewFieldSpec(paymentstatus.FieldID, field.TypeUUID))
	)
	if id, ok := psc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := psc.mutation.CreatedAt(); ok {
		_spec.SetField(paymentstatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := psc.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentstatus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := psc.mutation.Name(); ok {
		_spec.SetField(paymentstatus.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := psc.mutation.Description(); ok {
		_spec.SetField(paymentstatus.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	return _node, _spec
}

// PaymentStatusCreateBulk is the builder for creating many PaymentStatus entities in bulk.
type PaymentStatusCreateBulk struct {
	config
	err      error
	builders []*PaymentStatusCreate
}

// Save creates the PaymentStatus entities in the database.
func (pscb *PaymentStatusCreateBulk) Save(ctx context.Context) ([]*PaymentStatus, error) {
	if pscb.err != nil {
		return nil, pscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pscb.builders))
	nodes := make([]*PaymentStatus, len(pscb.builders))
	mutators := make([]Mutator, len(pscb.builders))
	for i := range pscb.builders {
		func(i int, root context.Context) {
			builder := pscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pscb *PaymentStatusCreateBulk) SaveX(ctx context.Context) []*PaymentStatus {
	v, err := pscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pscb *PaymentStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := pscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pscb *PaymentStatusCreateBulk) ExecX(ctx context.Context) {
	if err := pscb.Exec(ctx); err != nil {
		panic(err)
	}
}
