// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Debt is the predicate function for debt builders.
type Debt func(*sql.Selector)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// PaymentStatus is the predicate function for paymentstatus builders.
type PaymentStatus func(*sql.Selector)
